import hashlib
from typing import Optional


class AIContentDetector:
    def __init__(self):
        self.known_ai_hashes: set = set()
        self.patterns = [
            b"Generated by AI",
            b"AI-generated",
            b"DALL-E",
            b"Midjourney",
            b"Stable Diffusion",
            b"GPT",
            b"LLM",
            b"language model",
        ]

    def add_known_ai_hash(self, content_hash: str):
        self.known_ai_hashes.add(content_hash)

    def check_hash(self, content_hash: str) -> bool:
        return content_hash in self.known_ai_hashes

    def scan_metadata(self, data: bytes) -> float:
        """
        Simple heuristic scan for AI markers in content.
        Returns score 0.0 (human) to 1.0 (AI-generated).
        """
        score = 0.0
        matches = 0
        for pattern in self.patterns:
            if pattern.lower() in data.lower():
                matches += 1
        
        if matches > 0:
            score = min(1.0, matches * 0.2)
        
        # Check for AI metadata patterns
        ai_markers = [b"AI", b"artificial intelligence", b"neural network", b"transformer"]
        for marker in ai_markers:
            if marker.lower() in data.lower():
                score += 0.15
        
        return min(1.0, score)

    def analyze(self, data: bytes, mime_type: str, metadata: dict = None) -> dict:
        ai_score = self.scan_metadata(data)
        
        if metadata:
            ai_fields = metadata.get("ai_generated", metadata.get("generated_by_ai", None))
            if ai_fields:
                ai_score = max(ai_score, 0.8)

        return {
            "ai_generated_score": ai_score,
            "likely_human": ai_score < 0.3,
            "likely_ai": ai_score > 0.7,
            "uncertain": 0.3 <= ai_score <= 0.7,
            "method": "heuristic_scan"
        }
